// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// decode_ids_cpp
CharacterVector decode_ids_cpp(std::vector< std::string > new_id);
RcppExport SEXP _nflfastR_decode_ids_cpp(SEXP new_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector< std::string > >::type new_id(new_idSEXP);
    rcpp_result_gen = Rcpp::wrap(decode_ids_cpp(new_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nflfastR_decode_ids_cpp", (DL_FUNC) &_nflfastR_decode_ids_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_nflfastR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
