# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

decode_ids_cpp <- function(new_id) {
    .Call(`_nflfastR_decode_ids_cpp`, new_id)
}

